config/routes.rb
Rails.application.routes.draw do

	root "home#index"
	
	get 'about', to: "about#index"
	
	# Questions
	get 'questions', to: 'questions#index', as: :questions
	get 'questions/new', to: 'questions#new'
	get 'questions/:id', to: 'questions#show', as: :show_questions
	post 'questions', to: 'questions#create', as: :create_questions

	# Answers
	get 'questions/:id/answer', to: 'answers#new'
	post 'questions/:id/answer', to: 'answers#create', as: :create_answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  enum languages: [:css, :javascript, :ruby, :sql]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

	def	index
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	before_action :get_question, only: [:create]
	
	def	new
	end

	def create
		
		@answer = @question.answers.build(answer_params)
		if @answer.save
			redirect_to questions_path, notice: "Submitted an answer successfully."
		else
			render :new
		end
	end

	def show
	end

	private
	
	def answer_params
		params.require(:answer).permit(:text)
	end

	def get_question
		@question = Question.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.order('created_at')
	end

	def show
		@answer = Answer.new
		@redcarpet = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
		@question = Question.find(params[:id])
	end

	def	new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			redirect_to questions_path, notice: "Question has been created successfully."
		else
			render :new
		end
	end


	private
	def question_params
		params.require(:question).permit(:title)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def coderay text
		CodeRay.scan(text, :ruby).div(css: :class)
	end
end

app/views/about/index.html.erb
<div class="media">
	<div class="media-left media-top">
		<img class = "img-circle" src="<%= asset_path( 'profile.JPG' ) %>" width="400" height="400">	
	</div>

	<div class="jumbotron media-body">
		<h1>Harish Upadhyayula</h1>
		<p class="lead">
			I graduated in 2006, with Bachelors in Computer Science and started my career writing web applications using HTML, CSS, Jacascript, jQuery, ASP.NET, C#, Microsoft SQL Server. Lately, I started using Ruby on Rails, MySQL, MongoDB, Memcached, Perl, Python. Mostly, dabbling with open source.
		</p>
		<p class="lead">
			I am a Sr. Software Engineer at DealerSocket Inc. I am working on a SaaS product called Inventory+, where we write software to help car dealers manage their inventory, appraisals, sell cars on eBay, analytics and more.
		</p>
		<p class="lead">
			Lately, I have been working with the mobile team and building RESTful services to support mobile product.
		</p>
		<p><a class="btn btn-md btn-success" href="https://hupadhyayula.github.io" role="button">Link to my website.</a></p>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<h2>What I like</h2>
		<p>I enjoy reading, running and try <br> different beers and wine.</p>
	</div>
	<div class="col-lg-4">
		<h2>Some facts</h2>
		<p>I along with a team built an iPhone app called <br> JUXT and won the hackathon in the DFW area.</p>
		<a class="btn btn-default" href="http://ntc-dfw.org/ntx-apps-challenge-winners-2014/">View details »</a>
	</div>
	<div class="col-lg-4">
		<h2>Contact</h2>
		<p>You can reach me at:</p>
		<a class="btn btn-default" href="mailto:harish.upad@gmail.com">Email</a>
		<a class="btn btn-default" href="https://twitter.com/harishgeeth">Twitter</a>
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1>Welcome to Q'n'A</h1>
	<p>This app is an attempt to answer to some of HTML, CSS, Javascript, jQuery, Ruby, SQL and other supporting technology questions.</p>
	<p>These are pre-interview questions from Kalkomey.</p>
	<a class="btn btn-lg btn-success" href="/questions" role="button">See questions here...</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
		  <nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/">Q'n'A</a>
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="/questions">Questions</a></li>
		        <li><a href="/about">About me</a></li>
		      </ul>
		    </div>
		  </div>
		</nav>

  <body>
  	<div class="container">
  		<%= yield %>
  	</div>
  </body>
</html>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
	<% @questions.each do |question| %>
		
		<li>
			<%= link_to truncate(question.title, length: 80), show_questions_path(question) %>
		</li>

	<% end %>
</ul>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= form_for @question, url: {action: "create"} do |f| %>
	<div class='form-group'>
		<%= f.text_area :title %>
		<%= f.submit "Submit", class: 'btn btn-primary btn-lg', data: {disable_with: "Submit..."} %>
	</div>
<% end %>

app/views/questions/show.html.erb
<%= link_to "Questions", questions_path %>
<h1>Question</h1>

<p>
	<%= @redcarpet.render(@question.title).html_safe %>
</p>

<h1>Answers</h1>
<% @question.answers.each do |answer| %>
	<%= raw coderay(answer.text) %>
<% end %>

<%= form_for @answer, url: create_answers_path do |f| %>
	<%= f.text_area :text %>
	<%= f.button "Submit", class: 'btn btn-primary btn-lg', data: {disable_with: "Submit...."}  %>
<% end %>